[[_introducao]]
== Introdução

Muitos pensam que escrever sistemas eficazes, perfomáticos e resilientes são requisitos só para as grandes empresas da web como portais, redes sociais, etc. Porém, responder rápido a uma requisição, usar poucos recursos para atender bem e ser tolerante a falhas não devem ser requisitos de apenas *_grandes produtos_* com altos tráfegos e sim de todos que desejam entregar algo de qualidade para seu usuário.

Nenhum usuário irá voltar se seu site demorar demais para responder ou não estiver disponível por algum serviço que ele dependa estiver fora ou o site cair devido um grande volume de acessos (exemplo: sites de ingressos).

NOTE: Não precisa ser grande ou ter um número imenso de acesso para se preocupar com velocidade, resilienciar e vazão.


include::section/basico.adoc[]
include::section/sobre_perfomance.adoc[]
include::section/sobre_resiliencia.adoc[]

=== Resumo

É importante perceber que requisitos de ser rápido, atender certo volume de acessos, entre outras coisas similares, não são exclusividades de sistemas grandes, ou sistemas de grandes empresas, ou só do Twitter ou do Facebook. Vários textos sobre usabilidade dizem que a cada segundo de esperaum grande número de usuários desistem. Demorar significa perdir dinheiro.

Ser tolerante a falha é algo que deveria ser requisito de qualquer sistema. Nenhum sistema deveria falhar caso algo que esteja na sua _stack_ falhe. 
Enfim, bons sistemas, independente se foram feitos para 5 ou 50 milhões deveriam se preocupar com resiliência, perfomance e robustez. 
