[[_introducao]]
== Introdução

A questão de perfomance e alto desempenho deixou de ser uma preocupação somente de grande portais ou sistemas de grandes empresas. Hoje qualquer produto pode ter milhões de acessos. Outro ponto importante, é que a grande maioria dos usuários não terá paciência de esperar segundos para sua página carregar ou seu app (mobile por exemplo) abrir esperando aquela resposta da api no backend. 

Existe milhares de artigos na internet mostrando como as taxas de conversão (usuário acessar e comprar, usuário cotinuar navegando, etc) diminui a medida que o tempo de carregamento aumenta. 

Logo, tempo é dinheiro. 

Outro ponto importante, que com a enorme quantidade de opções, a chance de "conseguir" o clique é pequena. Sendo assim, imagina se o seu sistema sai do ar?

Por tudo isso, preocupar-se com perfomance, resiliência, suporte a alto tráfego, etc é muito importante.

Tendo isso em mente, abaixo serão descritos e explicados os pontos que servirão de base para todas as decisões que iremos tomar para termos sistemas de alto desempenho. Os pontos são os seguintes: Desempenho, Vazão, Resiliência e Falhas.

include::section/mito_maquina_barata.adoc[]
include::section/basico.adoc[]
include::section/sobre_perfomance.adoc[]
include::section/sobre_resiliencia.adoc[]

=== Resumo

Como já foi dito na introdução, qualidade é peça importante. Ela pode determinar se o produto terá sucesso ou não. Qualidade não está só associada a sistemas que façam o que se pede - extritamente; ela está ligada também a como esse serviço é entregue para usuário final. Nada adianta ter uma site com designer excelente se ele leva 10 segundos para carregar a página; nada adianta ter um fluxo muito bem implementado se ele falha se uma _API_ estiver fora deixando a todos frustado.

Existe um excelente livro, Release It, do Nygard, que diz que precisamos também nos preocupar com a vida do sistema no ar. Sua capacidade de se recuperar, tolerar um determinado volume, etc. Simplesmente fazer TDD e entregar o código fonte para ser deployado, não é estar PRONTO.

Robustez e eficácia são peças importantes no quebra-cabeça que compões bons aplicativos/sistemas. 

NOTE: Pronto é pronto para os usuários usarem.
