
=== Mito da Máquina Barata

Com diversos serviços de hospedagem e virtualização de infra, criou-se a ilusão de que _máquina_ é algo barato. Servidores se tornaram _commodites_. Essa ideia acabou se infiltrando no dia a dia dos desenvolvedores, fazendo com que a grande maioria deixe para um momento futuro tratar a qualidade de entrega do serviço. A grande maioria, criar sistemas, escolhe frameworks, e definem arquitetura, tendo como foco a facilidade de entrega de _features_, rapidez e integração, poucos ainda levam em consideração, tempo de resposta, quantidade de conexões simultaneas e tratamento de erros. Tudo porque, caso precisem de tempos menores, ou suportar maior vazão, _basta colocar mais máquina_ ... Mesmo com coisas como Amazon, Heroku, e similares, isso não é verdade e a conta no final do mês pode ficar bem cara. Esse caro pode ser em dinheiro gasto com a infrastrutura quanto em dinheiro não ganho por indisponibilidade do sistemas. 


NOTE: Nenhum processador, servidor, equipamento de rede, supera um bom código. 

Exemplos disse não faltam e _benchmarks_ para provar isso também. Além, existem casos que simplesmente colocar máquinas não é a solução sustentável. Casos como do Twitter, Netflix, Linkedin, e outros mostram isso claramente. Foi preciso mudar o foco. Foi preciso repensar a arquitetura e dar maior atenção a qualidade da entrega do serviço, fazendo mudanças de linguagens, frameworks e principalmente de arquiteturas. Foi preciso um olhar mais atento para seus algoritmos e estrutura de dados. Tanto que, decorrente disso, várias bibliotecas, livros e artigos inundaram o mercado, resultado de tal esforço por parte das empresas.

No livro de introdução ao algorítmo existe uma passagem interessante, quando as ordenações são apresentadas, ondem mesmo que o engenheiro usasse um super computador não superaria a melhoria trazida por um novo algoritmo. Só isso já basta para mostrar o quão importante é saber e conhecer bem os recursos disponíveis e fazer as melhores escolhas focadas na qualidade da entrega do serviço.  



